### PR TITLE
added virgilio and fixed href links

### PR DESCRIPTION
**Pull request by ninjatux**

### CODE REVIEW

**Comment by rands0n** [comment]
@NinjaTux Sorry for the delay. 

Thank you for this :)

**Comment by rands0n** [comment]
Same here, @NinjaTux can you check this issue #41? This framework has low number of stars.

Let's wait until a few weeks of 2015. If exceed 100 stars web keep here. Right?

**Comment by ninjatux** [comment]
of course but check the downloads in NPM :)
we are also working with [virgilio-http](https://github.com/icemobilelab/virgilio-http) and the two combined are generating more than 300 download monthly!

**Comment by rands0n** [comment]
Nice, thank you for that so! :)

**Pull request merged**
