### PR TITLE
add kona to mvc list

### PR DESCRIPTION
**Pull request by jbielick**
adds [kona](https://github.com/jbielick/kona) (based on Koa.js) to the MVC frameworks list

### CODE REVIEW

**Comment by rands0n** [comment]
This project has low number of stars. What you think @azat-co?

**Comment by jbielick** [comment]
@randsonjs if that's part of your criteria for posting this on your site, why would you not list in it in the instructions for contributing? Is this a website that merely features already popular frameworks for people who don't know how to search github, or is it a channel by which I can find a framework I wasn't aware of that has a concerted effort towards benefiting developer productivity and making tools / code available to more people?

Just trying not to waste my time here -- if I should come back when I have more stars, please indicate that somewhere so people know your vetting process / the standard by which you feature things.

**Comment by rands0n** [comment]
Hi @jbielick, it's very comprehensive of your part. I understand your question about the docs, really we do not put this in our contribution guide. If you search in others issues you'll see that the @azat-co speech most popular projects made in nodejs. So I asked the question to see what he thinks.

I really appreciate your contribution and your job at kona and myself would merge now.

Please do not close this issue and wait @azat-co answer and made a merge.

Glad of you contributing :)

**Comment by azat-co** [comment]
@jbielick @randsonjs sorry for the late response. social proof is not the best indicator of how good library is, but we have to use it because we cannot test every library extensively. the goal of nodeframework.com is to provide the best of the best. sorry if the submission process is not clear. maybe we can come up with some guide lines.

**Pull request closed without merging**
