### PR TITLE
Adding restling module.

### PR DESCRIPTION
**Pull request by lucasfeliciano**
I added to the list the module that I created.

It is a lib to make it easy to perform promise based http requests, including parallel requests.

### CODE REVIEW

**Comment by azat-co** [comment]
:+1:  thanks!

**Comment by azat-co** [comment]
@lucasfeliciano there is an issue with the info box, when you click on restling another box opens: https://www.dropbox.com/s/483d54g5jeh3vh3/Screenshot%202014-10-15%2019.02.17.png?dl=0

**Comment by azat-co** [comment]
I had to revert your PR until you fix it

https://github.com/azat-co/nodeframework/pull/32

**Comment by lucasfeliciano** [comment]
Sorry about that, I'm fixing it.

**Comment by azat-co** [comment]
@lucasfeliciano i reverted the first PR, could you make one with a your new fix?

**Comment by azat-co** [comment]
@randsonjs is this correct with the other PR?

**Comment by lucasfeliciano** [comment]
I opened another pull request and referenced this topic.

https://github.com/azat-co/nodeframework/pull/33

**Comment by rands0n** [comment]
I commented on pull request #33 :)

**Pull request merged**
