### PR TITLE
Add full-stack framework Danf

### PR DESCRIPTION
**Pull request by Gnucki**
Danf is a javascript/node full-stack framework providing many features in order to produce an evolutionary, maintainable, testable and performant code:
- An object-oriented programming layer.
- An inversion of control design (dependency injection via configurations files).
- A simple system allowing to use the same code on both the client and server sides.
- A homogeneous way to handle all kind of events (http request, dom events, ...).
- An elegant solution to callback hell preserving asynchronicity.
- A helper to develop performant ajax applications supporting deep linking.
- A modular approach to develop and use (open source) modules.

### CODE REVIEW

**Comment by rands0n** [comment]
:+1:

**Comment by Gnucki** [comment]
Thank you Randson. I prepare a presentation/tutorial site for the framework. It should be available in the early 2015.

**Comment by azat-co** [comment]
@Gnucki @randsonjs thank you!

**Comment by Gnucki** [comment]
Thank you to you!

**Comment by azat-co** [comment]
@Gnucki just realized that this framework has low number of stars... if you can get this number at least to 100 in the next couple weeks we'll keep it on the list... otherwise we'll have to remove it because NF is only for the most popular /social proven frameworks.

**Comment by rands0n** [comment]
Right @azat-co. Let's wait until a few weeks of 2015. If exceed 100 stars keep here. What you think?

**Comment by Gnucki** [comment]
Yes, I totally understand. I'm working on it actively even if I doubt to have 100 stars in a couple of weeks. Thank you to let it that weeks!

Danf is certainly not the best framework of the world but it can certainly have a little community because it offers its own paradigm and allows to easily share open source codes between developers. It is also certainly possible to code adapters to use it with other big frameworks in order to use OOP and dependency injection that it provides.

Like I said in my previous comment an original website should be available in the early 2015 to present and help to learn the framework in a pedagogical and fun way.

**Pull request merged**
