### PR TITLE
add FoollJS

### PR DESCRIPTION
**Pull request by burawi**
I added FoollJS a newely created framework

### CODE REVIEW

**Comment by rands0n** [comment]
@burawi can you resolve the conflicts with the base branch?

I think that's because the merges i've done in the last two pr's.

**Comment by rands0n** [comment]
The lines of modification is too much, you changed all the `index.html` file to insert the FoollJS? 😦

**Comment by burawi** [comment]
so how should I add it ?

**Comment by rands0n** [comment]
@burawi can you open a new pull request with the changes? or just edit the file with what changes you want and send another commit.

**Comment by rands0n** [comment]
sorry for the delay

**Pull request closed without merging**
