### PR TITLE
Added nuke.js full-stack framework

### PR DESCRIPTION
**Pull request by FREEZX**
This adds a new primus-based full-stack framework called nuke.js

### CODE REVIEW

**Comment by Gnucki** [comment]
You should certainly publish it on NPM and set the corresponding link.

**Comment by FREEZX** [comment]
@Gnucki i should first build a yeoman generator to be able to publish to npm, as this is more of a project boilerplate similar to meanjs.

**Comment by Gnucki** [comment]
Of course, this is another possibility!

**Comment by FREEZX** [comment]
@Gnucki Until then, this is what i have and works, but i'm unable to publish on npm due to the structure of the project.

**Comment by rands0n** [comment]
Hey @azat-co. This project have few stars. What you think about merge this PR?

**Comment by FREEZX** [comment]
I created a yeoman generator for generating nuke.js projects

**Comment by azat-co** [comment]
Probably we should hold on with putting it up the site until it's published on NPM and has a strong following or we personally try and like it.

**Comment by FREEZX** [comment]
It is published on npm and it's growing pretty fast.  https://www.npmjs.com/package/generator-nukejs

**Pull request merged**
