### PR TITLE
fix data-toggle id for restling

### PR DESCRIPTION
**Pull request by lucasfeliciano**
Fixed data-toggle id for restling module #31

### CODE REVIEW

**Comment by rands0n** [comment]
@lucasfeliciano this PR it's not working. You need change the `<div id="myid" class="panel-collapse collapse"` too. Only change the `id` attribute for name `restling` :)

**Comment by lucasfeliciano** [comment]
Yeah, the PR #31 what with this bug but I fix it in this PR #33

**Comment by rands0n** [comment]
The PR #31 was reverted. Remake this change in this PR.

Add more commits here :)

**Comment by lucasfeliciano** [comment]
I had to delete the my forked repository, I'll make another pull request because github lost the reference.

`lucasfeliciano  wants to merge 1 commit into azat-co:gh-pages from *unknown repository*`

**Pull request closed without merging**
